In [1]:
import numpy as np

#### Numpy array creation

In [2]:
np.array([1,3,4,5])

array([1, 3, 4, 5])

In [3]:
data = [ [1,2],[11,22],[111,222]]
a = np.array(data)
print(a)
print(type(a))

[[  1   2]
 [ 11  22]
 [111 222]]
<class 'numpy.ndarray'>


In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

#### Numpy arrays contain only one type

In [6]:
a = np.array([1.0, "is", True])
print(a)

['1.0' 'is' 'True']


#### Different use of + in Python and Numpy

In [8]:
python_list = [1,2,3]
np_list = np.array([1,2,3])
print(python_list + python_list)
print(np_list + np_list)

[1, 2, 3, 1, 2, 3]
[2 4 6]


#### Numpy Subsetting

In [9]:
bmi = np.array([10,30,50,70])
print(bmi[2])
print(bmi>35)
print(bmi[bmi>35])

50
[False False  True  True]
[50 70]


In [12]:
an_array=np.array([[1,2,3,4,5],[11,12,13,14,15]])
print(an_array)
print(an_array[0])
print(an_array[0][2])
print(an_array[0,2])
print(an_array[:, 1:3])

[[ 1  2  3  4  5]
 [11 12 13 14 15]]
[1 2 3 4 5]
3
3
[[ 2  3]
 [12 13]]


#### Numpy Utilities   
1. create a 2 X 2 array of zeros   
2. create a 2 X 2 array filled with 9.0  
3. create a 2 X 2 matrix with the diagonal 1s and the other 0  
4. create a array of ones
5. create an array of random floats between 0 and 1

In [16]:
print(np.zeros((2,2)))

[[0. 0.]
 [0. 0.]]


In [17]:
print(np.full((2,2), 9.0))

[[9. 9.]
 [9. 9.]]


In [18]:
print(np.eye(2,2))

[[1. 0.]
 [0. 1.]]


In [19]:
print(np.ones((2,2)))

[[1. 1.]
 [1. 1.]]


In [20]:
print(np.random.random((2,2)))

[[0.61519574 0.55055799]
 [0.24283783 0.01798407]]


In [21]:
an_array = np.array([ [11,12,13,14],[21,22,23,24],[31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [23]:
a_slice = an_array[:2, 1:3]
print(a_slice)

[[12 13]
 [22 23]]


In [25]:
a = np.arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [26]:
b = a.reshape(3,5)
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [27]:
print(b[:2,2:3])

[[2]
 [7]]


In [28]:
print(a[0:5:2])

[0 2 4]


In [29]:
print(a[::2])

[ 0  2  4  6  8 10 12 14]


In [31]:
print("Before: ", an_array[0,1])
a_slice[0,0] = 1000
print("After: ", an_array[0,1])

Before:  12
After:  1000


In [32]:
an_array = np.array([ [11,12,13,14],[21,22,23,24],[31,32,33,34]])
print(an_array)
row_rank1 = an_array[1,:]
print(row_rank1, row_rank1.shape)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]
[21 22 23 24] (4,)


In [33]:
row_rank2=an_array[1:2,:]
print(row_rank2, row_rank2.shape)

[[21 22 23 24]] (1, 4)


In [35]:
col_rank1 = an_array[:,1]
col_rank2 = an_array[:,1:2]
print(col_rank1,col_rank1.shape)
print(col_rank2,col_rank2.shape)

[12 22 32] (3,)
[[12]
 [22]
 [32]] (3, 1)


In [36]:
an_array = np.array([ [11,12,13,14],[21,22,23,24],[31,32,33,34],[41,42,43,44]])
print(an_array)
print(an_array.shape)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]
 [41 42 43 44]]
(4, 4)


In [37]:
row_indices = np.arange(4)
col_indices = np.array([0,1,2,0])
print(row_indices)
print(col_indices)
print(zip(row_indices, col_indices))

[0 1 2 3]
[0 1 2 0]


In [38]:
for row, col in zip(row_indices, col_indices):
    print(row, " ",col)

0   0
1   1
2   2
3   0


In [39]:
print("values: \n", an_array[row_indices,col_indices])

values: 
 [11 22 33 41]


In [40]:
an_array=np.array([ [11,12],[21,22],[31,32]])
filter = (an_array>15) 
print(an_array)
print(filter)

[[11 12]
 [21 22]
 [31 32]]
[[False False]
 [ True  True]
 [ True  True]]


In [41]:
print(an_array[filter])

[21 22 31 32]


In [42]:
an_array[an_array>15]

array([21, 22, 31, 32])

In [43]:
a =np.array(range(8))
print(a)
print(a.shape)

[0 1 2 3 4 5 6 7]
(8,)


In [44]:
b=a.reshape((a.shape[0],1))
print(b)
print(b.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
(8, 1)


In [45]:
c=a.reshape(2,4)
print(c)

[[0 1 2 3]
 [4 5 6 7]]


In [46]:
d=a.reshape(2,2,2)
print(d)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [47]:
b=np.arange(12).reshape(2,6)
print(b)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [49]:
d=b.reshape(3,-1)
print(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
