In [70]:
import pandas as pd

In [71]:
df = pd.read_csv('train.csv')
df

신고번호        신고일자  통관지세관부호  신고인부호    수입자부호  해외거래처부호  특송업체부호  \
0      57298928  2020-01-01      121  2O5A2  82ZHWNL      NaN  TQ18AK   
1      85092852  2020-01-01       30  305K5  5IS70LE      NaN     NaN   
2      63014158  2020-01-01       20  CGMT6  GJ5KBL3  R9ZQOG7     NaN   
3      40175917  2020-01-01       40  QWUTG  PBYW02T      NaN     NaN   
4      11602631  2020-01-01       30  0X1CO  MCX0GJB  4Z9PX0Y     NaN   
...         ...         ...      ...    ...      ...      ...     ...   
89350  78046993  2020-11-22       10  M9SYU  K8195QD      NaN  PR5UFJ   
89351  85641293  2020-11-22       41  T7VQN  MSE4EAG      NaN     NaN   
89352  15760215  2020-11-22       40  7Q31W  5BC6UCR  QW3LA8B     NaN   
89353  20569033  2020-11-22       40  UJ0JR  U7KJPA6  TJW57CJ  O04TIW   
89354  79725596  2020-11-22       30  4TUUB  J2D5UL7  0UOB77D     NaN   

      수입통관계획코드 수입신고구분코드  수입거래구분코드  ...      과세가격원화금액  운송수단유형코드  반입보세구역부호  \
0            D        B        15  ...  5.397966e+03        10   2106003   
1            C        B        11  ...  5.730972e+05        40   4077010   
2            D        B        11  ...  5.219489e+04        40   4077007   
3            C        B        94  ...  1.773608e+06        40   4077106   
4            C        B        11  ...  8.777327e+06        40   2006075   
...        ...      ...       ...  ...           ...       ...       ...   
89350        C        B        11  ...  9.139535e+04        10   4002001   
89351        E        E        15  ...  3.752803e+04        40   4077008   
89352        C        B        29  ...  1.381431e+04        10   2086001   
89353        F        B        15  ...  4.030176e+03        40   1618003   
89354        Z        B        15  ...  1.545601e+03        10   3078039   

         HS10단위부호  적출국가코드  원산지국가코드  관세율구분코드    관세율 우범여부 핵심적발  
0      8481900000      US       US        A    8.0    1    1  
1      2106909099      US       US        A    8.0    0    0  
2      6307909000      US       US        A   10.0    0    0  
3      6505009090      CN       CN        A    8.0    0    0  
4      6204320000      CN       CN     FCN1    5.2    1    1  
...           ...     ...      ...      ...    ...  ...  ...  
89350   703101000      CN       CN       W2  135.0    0    0  
89351  6804220000      CN       CN     FCN1    0.0    0    0  
89352  8210005000      CN       CN        A    8.0    0    0  
89353  3304999000      CA       CA        C    6.5    1    2  
89354  3304999000      HK       HK        C    6.5    0    0  

[89355 rows x 23 columns]

### 신고일자 column에서 달만 추출

In [72]:
df['신고일자']=pd.to_datetime(df['신고일자'])   #datetime으로
df['신고일자_월'] = df['신고일자'].dt.month

In [73]:
df['신고일자_월'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int64)

### 신고인부호

In [74]:
df['신고인부호'].unique()

array(['2O5A2', '305K5', 'CGMT6', 'QWUTG', '0X1CO', 'QV6WA', 'BTMNQ',
       '9TJBD', 'ZAV8X', 'RDDA3', 'WN68Z', 'LDZ42', 'JCOIV', '7Z767',
       '90DJS', 'HOSTX', 'D2LHR', 'J9SYX', 'D3UN5', 'QUP4L', 'ZWWQR',
       'Z5KQD', 'XNLY5', 'QPV57', 'ZYM25', 'FQSF7', '9J612', 'YBA4D',
       'WTDS3', 'ZEWOY', 'JMTO5', 'N8ZDA', '3A8I7', '48BVY', 'QWXA9',
       'EX3CM', 'CAG89', 'GXAPH', 'YNURP', 'FLZF8', 'MFVGQ', '7TNHP',
       'WX0PH', 'ZIWZ5', 'VXXBS', 'WGUGM', 'M7H00', '82RO1', 'VTAHP',
       'QOW7F', 'F6BJB', 'VRNEF', '6WN08', 'S7YY8', '5F3BP', 'NX7FG',
       'LNXE0', 'KFCKA', '53W8N', '0ZK7G', 'W1SD2', 'PWT1V', 'ZFKMC',
       '6YV1J', '6E1FQ', '8LF89', 'FCS2Y', 'SVDN5', '2DOHT', 'MELHS',
       '5PMW1', 'H2IMQ', '61KA7', '2RRV1', 'ROTPV', 'B1LIZ', 'WLX9V',
       '7OKD7', 'ICDM1', '0A0V6', 'XMKTR', 'MSWFH', '7Q31W', 'Z3EO2',
       '7EWOF', '0BCW8', '4U9GW', 'ZUJ45', '8WH99', 'M26RC', 'DGKGI',
       'BOMUQ', '379YD', '50BZJ', 'XQKDE', 'K2QZ9', 'UE64N', '00Z2U',
       '62P2N', 'DDY

### 수입자부호

In [75]:
df['수입자부호'].unique()

array(['82ZHWNL', '5IS70LE', 'GJ5KBL3', ..., 'N65MJ0E', '2K7ZFS0',
       'MROTHDM'], dtype=object)

In [76]:
df['수입자부호'].value_counts(dropna=False)

82ZHWNL    400
VDQCE8U    351
18FVF01    287
O8B0380    247
DA4FLAJ    240
          ... 
8H2XVYZ      1
934DM9O      1
GBNQKGG      1
EHLLURA      1
ZLWPPFA      1
Name: 수입자부호, Length: 8417, dtype: int64

### 해외거래처부호

In [77]:
df['해외거래처부호'].unique()

array([nan, 'R9ZQOG7', '4Z9PX0Y', ..., 'YOZEPF2', '25SOSMN', 'NAB1I2E'],
      dtype=object)

In [78]:
df['해외거래처부호'].value_counts(dropna=False)

NaN        30432
WQZVLM0      594
R0XT3H9      413
MW8PLZN      406
VQJ47O3      379
           ...  
2OD6ZFQ        1
WR6SV17        1
E3F1P40        1
RZIV2V7        1
L0ISS36        1
Name: 해외거래처부호, Length: 4779, dtype: int64

Nan 처리해주기    
### 특송업체부호

In [79]:
df['특송업체부호'].unique()

array(['TQ18AK', nan, 'PAVJZL', 'VACAWV', 'QP5OME', 'ID7FLR', 'QJ0YGH',
       'L2ILSN', 'RG7BYC', 'TOO0OK', 'QSV8RY', 'PR5UFJ', '90DF54',
       'O04TIW', 'PZYUR4', 'HN5E27', 'A9QWI8', '24BG4R', 'KTBTZT',
       '5HIQAV', 'VSYNVB', '6AXUNR', 'C54WLZ', 'YBNP69', 'D3H0A4',
       '26O9QU', 'K35446', 'YXAKR4', 'CRVF1Z', 'XK2HKR', 'HGT4IX',
       'OJ6WM3', '9BO2S9', '6MSSDI', 'QKUSM1', '6TFEP5', '2ADDNP',
       'NBYTNK', 'L67RFP', 'Q8TBEO', 'RKP5AP', '8Z7M3O', '718MAA',
       '883CMC', 'XIKL72', '6RJ8HT', '47QGIA', '6VXR7R', '8Q2G59',
       '98GCBT', '1E2DJD', 'BLQXV7', '6EM00W', 'M72HED', 'HRIQ4G',
       'HB62YN', 'M7SEXF', '5SZ7FO', 'VI9G4M', 'Q03ZS4', 'FK5XHP',
       'RDEAWL', 'ME9TG4', 'O2J0OX', 'MWL4TG', 'KMQGJQ', 'FJ0YAA',
       'ZVCGS6', '1A3HEJ', 'YGHZ0X', 'WDVVLL', 'A41WVG', 'I8ST7N',
       'ID1L6P', 'MRD73X', '6FE43Q', 'AMGRF5', '5FDIRV', '1EZAFG',
       'PNE6WR', 'L0ZLXK'], dtype=object)

In [80]:
df['특송업체부호'].value_counts(dropna=False)

NaN       60050
PR5UFJ     5800
PAVJZL     3314
24BG4R     1425
TQ18AK     1311
          ...  
PNE6WR       30
ID1L6P       29
MWL4TG       21
M72HED       20
5FDIRV       17
Name: 특송업체부호, Length: 81, dtype: int64

Nan이 많은데 삭제하는게 나으려나..???
### 수입통관계획코드, 수입신고구분코드

In [81]:
df['수입통관계획코드'].unique()

array(['D', 'C', 'B', 'E', 'F', 'H', 'Z'], dtype=object)

In [82]:
df['수입신고구분코드'].unique()

array(['B', 'D', 'A', 'E'], dtype=object)

In [83]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
label = df['수입통관계획코드']
le.fit(label)
label_encoded = le.transform(label)

In [84]:
l_e_df = pd.DataFrame(label_encoded, columns=['label_encoded'])
df['수입통관계획코드'] = l_e_df
df['수입통관계획코드'].unique()

array([2, 1, 0, 3, 4, 5, 6])

In [85]:
label = df['수입신고구분코드']
le.fit(label)
label_encoded = le.transform(label)

In [86]:
l_e_df = pd.DataFrame(label_encoded, columns=['label_encoded'])
df['수입신고구분코드'] = l_e_df
df['수입신고구분코드'].unique()

array([1, 2, 0, 3])

label encoding으로 처리
### 적출국가코드, 원산지국가코드

In [87]:
df['적출국가코드'].unique()

array(['US', 'CN', 'JP', 'IN', 'TH', 'SG', 'TW', 'HK', 'IL', 'CA', 'MY',
       'NL', 'DE', 'AU', 'ES', 'IT', 'GB', 'VN', 'PR', 'AE', 'PA', 'EC',
       'SA', 'FR', 'KR', 'FI', 'RU', 'BE', 'KH', 'ID', 'PH', 'SE', 'MO',
       'MX', 'CL', 'BD', 'DK', 'SI', 'GU', 'EG', 'BR', 'NZ', 'PK', 'CH',
       'RO', 'MM', 'QA', 'KW', 'GR', 'MN', 'HU', 'AT', 'GN', 'TR', 'SN',
       'PT', 'NP', 'KG', 'EE', 'ZA', 'BN', 'LU', 'LV', 'PY', 'UZ', 'LK',
       'NO', 'PL', 'ET', 'SO', 'CZ', 'PE', 'SB', 'LT', 'OM', 'ZZ', 'LI',
       'BG', 'AS', 'CR', 'UG', 'HR', 'MG', 'DO', 'BH', 'IE', 'AR', 'NG',
       'MH'], dtype=object)

In [88]:
df['원산지국가코드'].unique()

array(['US', 'CN', 'JP', 'IN', 'IT', 'TH', 'SG', 'TW', 'IL', 'MY', 'VN',
       'TR', 'DE', 'AU', 'BG', 'GB', 'KR', 'PR', 'AE', 'HK', 'EC', 'SA',
       'CA', 'FR', 'KH', 'ID', 'FI', 'RU', 'PH', 'HU', 'SE', 'ZZ', 'MD',
       'PE', 'AT', 'BE', 'PL', 'MX', 'BD', 'DK', 'CL', 'ES', 'SI', 'VU',
       'BR', 'NZ', 'RO', 'PK', 'CH', 'MM', 'SK', 'NL', 'BW', 'GR', 'MN',
       'PT', 'NO', 'GN', 'LT', 'LK', 'SN', 'EG', 'ZA', 'IE', 'NP', 'MA',
       'HN', 'TN', 'KG', 'EE', 'PY', 'GU', 'UZ', 'CZ', 'SO', 'AR', 'HR',
       'SB', 'BA', 'OM', 'RS', 'SM', 'UA', 'WS', 'MG', 'GT', 'IR', 'BH',
       'BO', 'MO', 'NG', 'AM', 'MH', 'CR'], dtype=object)

### 관세율구분코드

In [89]:
df['관세율구분코드'].unique()

array(['A', 'FCN1', 'C', 'CIT', 'FIN1', 'FUS1', 'E1', 'FEU1', 'W2',
       'FCN2', 'L', 'FAU1', 'FUS6', 'FCA1', 'FAS1', 'P3', 'F', 'W1',
       'FUS5', 'FVN1', 'CIT1', 'FPE1', 'FCL1', 'FCN6', 'FNZ1', 'FEF1',
       'P1', 'FTR1', 'FSG1', 'FUS2', 'FVN2', 'R', 'FEU6', 'C3', 'FCN4'],
      dtype=object)

### int, float 형

In [90]:
df.describe()

신고번호       통관지세관부호      수입통관계획코드      수입신고구분코드      수입거래구분코드  \
count  8.935500e+04  89355.000000  89355.000000  89355.000000  89355.000000   
mean   5.492568e+07     33.121493      1.874187      1.057523     25.580494   
std    2.590161e+07     18.198064      1.235338      0.342149     29.214542   
min    1.000149e+07     10.000000      0.000000      0.000000     11.000000   
25%    3.252167e+07     20.000000      1.000000      1.000000     11.000000   
50%    5.490483e+07     40.000000      2.000000      1.000000     11.000000   
75%    7.737544e+07     40.000000      2.000000      1.000000     15.000000   
max    9.999869e+07    154.000000      6.000000      3.000000     96.000000   

             수입종류코드        징수형태코드       신고중량(KG)      과세가격원화금액      운송수단유형코드  \
count  89355.000000  89355.000000   89355.000000  8.935500e+04  89355.000000   
mean      20.322903     15.644541    8524.613459  8.008072e+07     26.164065   
std        2.721040     10.675386   12581.507315  5.825281e+09     15.514324   
min       11.000000      0.000000       0.100000  0.000000e+00     10.000000   
25%       21.000000     11.000000    1473.800000  5.248629e+04     10.000000   
50%       21.000000     11.000000    5803.600000  3.929485e+05     40.000000   
75%       21.000000     14.000000    9869.450000  2.600951e+06     40.000000   
max       28.000000     43.000000  216803.100000  6.952264e+11     90.000000   

           반입보세구역부호      HS10단위부호           관세율          우범여부          핵심적발  \
count  8.935500e+04  8.935500e+04  89355.000000  89355.000000  89355.000000   
mean   3.114182e+06  5.781345e+09      8.441745      0.230093      0.348509   
std    1.593484e+06  2.754415e+09     29.536271      0.420895      0.681092   
min    1.002014e+06  1.012990e+08      0.000000      0.000000      0.000000   
25%    2.006099e+06  3.402110e+09      0.000000      0.000000      0.000000   
50%    3.077098e+06  6.205200e+09      6.500000      0.000000      0.000000   
75%    4.077003e+06  8.515110e+09      8.000000      0.000000      0.000000   
max    1.540200e+07  9.706009e+09    800.300000      1.000000      2.000000   

             신고일자_월  
count  89355.000000  
mean       5.602596  
std        3.120887  
min        1.000000  
25%        3.000000  
50%        6.000000  
75%        8.000000  
max       11.000000

In [95]:
df=df.describe()
df

신고번호       통관지세관부호      수입통관계획코드      수입신고구분코드      수입거래구분코드  \
count  8.935500e+04  89355.000000  89355.000000  89355.000000  89355.000000   
mean   5.492568e+07     33.121493      1.874187      1.057523     25.580494   
std    2.590161e+07     18.198064      1.235338      0.342149     29.214542   
min    1.000149e+07     10.000000      0.000000      0.000000     11.000000   
25%    3.252167e+07     20.000000      1.000000      1.000000     11.000000   
50%    5.490483e+07     40.000000      2.000000      1.000000     11.000000   
75%    7.737544e+07     40.000000      2.000000      1.000000     15.000000   
max    9.999869e+07    154.000000      6.000000      3.000000     96.000000   

             수입종류코드        징수형태코드       신고중량(KG)      과세가격원화금액      운송수단유형코드  \
count  89355.000000  89355.000000   89355.000000  8.935500e+04  89355.000000   
mean      20.322903     15.644541    8524.613459  8.008072e+07     26.164065   
std        2.721040     10.675386   12581.507315  5.825281e+09     15.514324   
min       11.000000      0.000000       0.100000  0.000000e+00     10.000000   
25%       21.000000     11.000000    1473.800000  5.248629e+04     10.000000   
50%       21.000000     11.000000    5803.600000  3.929485e+05     40.000000   
75%       21.000000     14.000000    9869.450000  2.600951e+06     40.000000   
max       28.000000     43.000000  216803.100000  6.952264e+11     90.000000   

           반입보세구역부호      HS10단위부호           관세율          우범여부          핵심적발  \
count  8.935500e+04  8.935500e+04  89355.000000  89355.000000  89355.000000   
mean   3.114182e+06  5.781345e+09      8.441745      0.230093      0.348509   
std    1.593484e+06  2.754415e+09     29.536271      0.420895      0.681092   
min    1.002014e+06  1.012990e+08      0.000000      0.000000      0.000000   
25%    2.006099e+06  3.402110e+09      0.000000      0.000000      0.000000   
50%    3.077098e+06  6.205200e+09      6.500000      0.000000      0.000000   
75%    4.077003e+06  8.515110e+09      8.000000      0.000000      0.000000   
max    1.540200e+07  9.706009e+09    800.300000      1.000000      2.000000   

             신고일자_월  
count  89355.000000  
mean       5.602596  
std        3.120887  
min        1.000000  
25%        3.000000  
50%        6.000000  
75%        8.000000  
max       11.000000

신고중량(KG), 과세가격원화금액, 반입보세구역부호, HS10단위부호: feature scaling 필요    
     
트리 모델: feature scaling 필요 없음, 라벨 인코딩 가능

In [91]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89355 entries, 0 to 89354
Data columns (total 24 columns):
 #   Column    Non-Null Count  Dtype         
---  ------    --------------  -----         
 0   신고번호      89355 non-null  int64         
 1   신고일자      89355 non-null  datetime64[ns]
 2   통관지세관부호   89355 non-null  int64         
 3   신고인부호     89355 non-null  object        
 4   수입자부호     89346 non-null  object        
 5   해외거래처부호   58923 non-null  object        
 6   특송업체부호    29305 non-null  object        
 7   수입통관계획코드  89355 non-null  int32         
 8   수입신고구분코드  89355 non-null  int32         
 9   수입거래구분코드  89355 non-null  int64         
 10  수입종류코드    89355 non-null  int64         
 11  징수형태코드    89355 non-null  int64         
 12  신고중량(KG)  89355 non-null  float64       
 13  과세가격원화금액  89355 non-null  float64       
 14  운송수단유형코드  89355 non-null  int64         
 15  반입보세구역부호  89355 non-null  int64         
 16  HS10단위부호  89355 non-null  int64         
 17  적출국가코드    89

In [4]:
import csv
import matplotlib.pyplot as plt
%matplotlib inline
x=[]
z=[]
f = open("train.csv",'rt', encoding='UTF8')
for row in csv.reader(f):
    x.append(row[0])
    z.append(row[1])
    
plt.plot(x, z, 'r.')
plt.axis([-1, 30, -5,1 ])
plt.show()

KeyboardInterrupt: 

In [1]:
%matplotlib inline
import pandas as pd                # 데이터를 저장하고 처리하는 패키지
import matplotlib as mpl           # 그래프를 그리는 패키지
import matplotlib.pyplot as plt    # 그래프를 그리는 패키지

In [19]:
df = pd.read_csv('train.csv', encoding='UTF8')
# origin_df = df.loc[[' US', ' CN', ' JP', ' IN', ' IT', ' TH', ' SG']]
# orgin_df

In [14]:
df['원산지국가코드']

0        US
1        US
2        US
3        CN
4        CN
         ..
89350    CN
89351    CN
89352    CN
89353    CA
89354    HK
Name: 원산지국가코드, Length: 89355, dtype: object

In [20]:
x_columns = ['원산지국가코드']
y_columns = ['우범여부']

df.plot(x=x_columns, y=y_columns)
plt.show()

ValueError: x must be a label or position

In [21]:
df['우범여부']

0        1
1        0
2        0
3        0
4        1
        ..
89350    0
89351    0
89352    0
89353    1
89354    0
Name: 우범여부, Length: 89355, dtype: int64

In [92]:
df.head(3)

신고번호       신고일자  통관지세관부호  신고인부호    수입자부호  해외거래처부호  특송업체부호  수입통관계획코드  \
0  57298928 2020-01-01      121  2O5A2  82ZHWNL      NaN  TQ18AK         2   
1  85092852 2020-01-01       30  305K5  5IS70LE      NaN     NaN         1   
2  63014158 2020-01-01       20  CGMT6  GJ5KBL3  R9ZQOG7     NaN         2   

   수입신고구분코드  수입거래구분코드  ...  운송수단유형코드  반입보세구역부호    HS10단위부호  적출국가코드  원산지국가코드  \
0         1        15  ...        10   2106003  8481900000      US       US   
1         1        11  ...        40   4077010  2106909099      US       US   
2         1        11  ...        40   4077007  6307909000      US       US   

   관세율구분코드   관세율 우범여부 핵심적발 신고일자_월  
0        A   8.0    1    1      1  
1        A   8.0    0    0      1  
2        A  10.0    0    0      1  

[3 rows x 24 columns]

In [25]:
from sklearn.model_selection import '우범여부'

SyntaxError: invalid syntax (<ipython-input-25-362c33ed1189>, line 1)

## LightGBM
섬머스쿨 응용

In [98]:
from lightgbm import LGBMClassifier
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split

dataset = df
ftr = dataset.data
target = dataset.target

# 전체 데이터 중 80%는 학습용 데이터, 20%는 테스트용 데이터 추출
X_train, X_test, y_train, y_test = train_test_split(ftr, target,
                                                   test_size=0.2, random_state=156)

#앞서 XGBoost와 동일하게 n_estimators는 400 설정
lgbm_wrapper = LGBMClassifier(n_estimators=400)

# LightGBM도 XGBoost와 동일하게 조기 중단 수행 가능.
evals = [(X_test, y_test)]
lgbm_wrapper.fit(X_train, y_train, early_stopping_rounds=100, eval_metric="logloss",
                 eval_set=evals, verbose=True)
preds = lgbm_wrapper.predict(X_test)
pred_proba = lgbm_wrapper.predict_proba(X_test)[:,1]

AttributeError: 'DataFrame' object has no attribute 'data'

데이터 전처리

In [96]:
dataset = df
dataset.fillna('', inplace=True)
X = dataset.iloc[:, [2, 3]].values
y = dataset.iloc[:, 4].values
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

## XGBoost

In [97]:
import xgboost as xgb
dataset = df
X = dataset.iloc[:, [2, 3]].values
y = dataset.iloc[:, 4].values
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

 
dtrain = xgb.DMatrix(data = X_train, label = y_train)
dtest = xgb.DMatrix(data = X_test, label = y_test)
 
params = {
    'max_depth' : 3,
    'eta' : 0.001,
    'objective' : 'binary:logistic',
    'eval_metric' : 'logloss',
    'early_stoppings' : 100
}
 
 
num_rounds = 400
 
wlist = [(dtrain, 'train'), (dtest,'eval')]
xgb_model = xgb.train(params = params, dtrain = dtrain, num_boost_round= num_rounds, evals = wlist)
pred_probs = xgb_model.predict(dtest)
print("predict() 수행 결과값을 10개만 표시, 예측 확률값으로 표시됨")
print(np.round(pred_probs[:10],3))
 
preds = [1 if x >0.5 else 0 for x in pred_probs]
print("예측값 10개만 표시 : ", pred[:10])
get_clf_eval(y_test,preds)


[22:14:00] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:573: 
Parameters: { "early_stoppings" } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.




XGBoostError: [22:14:00] C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/objective/regression_obj.cu:103: label must be in [0,1] for logistic regression

### Label Encoder

In [40]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

label_plan = df['수입통관계획코드']
label_plan.unique()

array(['D', 'C', 'B', 'E', 'F', 'H', 'Z'], dtype=object)

In [41]:
le.fit(label_plan)

LabelEncoder()

In [44]:
label_plan_encoded = le.transform(label_plan)
label_plan_encoded

array([2, 1, 2, ..., 1, 4, 6])

In [47]:
type(label_plan_encoded)

numpy.ndarray

In [48]:
df['수입통관계획코드']= label_plan_encoded

In [62]:
label_declare = df['수입신고구분코드']
le.fit(label_declare)
label_declare_encoded = le.transform(label_declare)
df['수입신고구분코드'] = label_declare_encoded
df

신고번호        신고일자  통관지세관부호  신고인부호    수입자부호  해외거래처부호  특송업체부호  \
0      57298928  2020-01-01      121     65  82ZHWNL      NaN  TQ18AK   
1      85092852  2020-01-01       30     75  5IS70LE      NaN     NaN   
2      63014158  2020-01-01       20    319  GJ5KBL3  R9ZQOG7     NaN   
3      40175917  2020-01-01       40    722  PBYW02T      NaN     NaN   
4      11602631  2020-01-01       30     25  MCX0GJB  4Z9PX0Y     NaN   
...         ...         ...      ...    ...      ...      ...     ...   
89350  78046993  2020-11-22       10    610  K8195QD      NaN  PR5UFJ   
89351  85641293  2020-11-22       41    774  MSE4EAG      NaN     NaN   
89352  15760215  2020-11-22       40    207  5BC6UCR  QW3LA8B     NaN   
89353  20569033  2020-11-22       40    804  U7KJPA6  TJW57CJ  O04TIW   
89354  79725596  2020-11-22       30    130  J2D5UL7  0UOB77D     NaN   

       수입통관계획코드  수입신고구분코드  수입거래구분코드  ...      과세가격원화금액  운송수단유형코드  반입보세구역부호  \
0             2         1        15  ...  5.397966e+03        10   2106003   
1             1         1        11  ...  5.730972e+05        40   4077010   
2             2         1        11  ...  5.219489e+04        40   4077007   
3             1         1        94  ...  1.773608e+06        40   4077106   
4             1         1        11  ...  8.777327e+06        40   2006075   
...         ...       ...       ...  ...           ...       ...       ...   
89350         1         1        11  ...  9.139535e+04        10   4002001   
89351         3         3        15  ...  3.752803e+04        40   4077008   
89352         1         1        29  ...  1.381431e+04        10   2086001   
89353         4         1        15  ...  4.030176e+03        40   1618003   
89354         6         1        15  ...  1.545601e+03        10   3078039   

         HS10단위부호  적출국가코드  원산지국가코드  관세율구분코드    관세율 우범여부 핵심적발  
0      8481900000      US       US        A    8.0    1    1  
1      2106909099      US       US        A    8.0    0    0  
2      6307909000      US       US        A   10.0    0    0  
3      6505009090      CN       CN        A    8.0    0    0  
4      6204320000      CN       CN     FCN1    5.2    1    1  
...           ...     ...      ...      ...    ...  ...  ...  
89350   703101000      CN       CN       W2  135.0    0    0  
89351  6804220000      CN       CN     FCN1    0.0    0    0  
89352  8210005000      CN       CN        A    8.0    0    0  
89353  3304999000      CA       CA        C    6.5    1    2  
89354  3304999000      HK       HK        C    6.5    0    0  

[89355 rows x 23 columns]

In [63]:
label = df['신고인부호']
le.fit(label)
label_encoded = le.transform(label)
df['신고인부호'] = label_encoded